name: Build and Setup React Application in S3
on:
  push:
    branches: [ main, staging ]

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set branch
        run: |
          if [[ $GITHUB_REF_NAME != 'main' ]]; then
            echo "TF_WORKSPACE" == $GITHUB_REF_NAME
          fi
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
      - name: Output build files
        uses: actions/setup-node@v1
        with:
          node-version: 17.9.0
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}
        working-directory: ./client
      - name: Install dependencies 
        run: npm install
        working-directory: ./client

      - name: Build Application
        run: npm run build
        working-directory: ./client

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
